server:
  port: #server port
  bind: #server binding address
database:
  user: #database username (is assumed the MySQL instance is the same)
  password: #database password
  host: #database host
default_redmine:
  db_name: #default redmine database name
pd_redmine:
  db_name: #P&D instance database name
